---
- hosts: all
  become: yes
  tasks:
  - name: install net-tools
    apt:
      name: net-tools
      state: present
  - name: install git
    shell: apt install git -y
  - name: install nano
    apt:
      name: nano
      state: present
  - name: install maven
    apt:
      name: maven
      state: present
