- name: Install Docker on Ubuntu
  hosts: localhost
  become: yes  # Run as sudo
  tasks:

    - name: Update apt packages
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: Add Docker repository
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

    - name: Update apt packages again
      apt:
        update_cache: yes

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to Docker group (optional)
      user:
        name: "{{ ansible_user | default('ubuntu') }}"
        groups: docker
        append: yes
