---
- hosts: all
  become: yes
  tasks:
  - name: install nodejs package
    ansible.builtin.apt:
      name: nodejs
      state: present
  - name: install npm package
    ansible.builtin.apt:
      name: npm
      state: present
