---
- hosts: all
  tasks:
    - name: Update APT package manager repositories cache
      become: no
      apt:
        update_cache: yes
    - name: Install Java using Ansible
      become: no
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - openjdk-11-jdk
