---
- hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Perform apt update
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    shell: apt update
  - name: Install Nginx
    when: ansible_distribution == 'Ubuntu'
    shell: apt install -y nginx
  - name: Start Nginx Service
    when: ansible_distribution == 'Ubuntu'
    shell: service nginx start
  - name: install unzip
    apt:
      name: unzip
      state: present
  tags:
    - nginx

- name: Copy Files To All
  hosts: all
  become: yes
  tasks:
  - name: Remove Default Nginx File
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    shell: rm -rf /var/www/html/index.nginx-debian.html
  - name: Copy WebServer Files
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /var/www/html/{{ item }}
      owner: root
      group: root
      mode: '0644'
    with_items:
      - index.html
      - scorekeeper.js
      - style.css
    notify: restart_nginx

  handlers:
  - name: restart_nginx
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    shell: service nginx restart
  tags:
    - files
